nodeLinker: node-modules

npmPublishRegistry: "https://europe-west1-npm.pkg.dev/siren-cicd/npm-standard/"

npmScopes:
  antv:
    npmRegistryServer: "https://europe-west1-npm.pkg.dev/siren-cicd/npm-virtual/"
