nodeLinker: node-modules

npmPublishRegistry: "https://europe-west1-npm.pkg.dev/siren-cicd/npm-standard/"

npmScopes:
  antv:
    npmRegistryServer: "https://europe-west1-npm.pkg.dev/siren-cicd/npm-virtual/"

yarnPath: .yarn/releases/yarn-4.5.1.cjs

plugins:
  - checksum: 7a993ef2944928530db74ca2f844dc21324bdc768bb0744b772277b114f28da4625903f4109fc90f3de6621e97c646f8969167df3435ee7e443d79b8a4806a62
    path: .yarn/plugins/@sirensolutions/yarn-plugin-gar-auth.cjs
    spec: "@sirensolutions/yarn-plugin-gar-auth.cjs"
