nodeLinker: node-modules

npmScopes:
  antv:
    npmRegistryServer: "https://europe-west1-npm.pkg.dev/siren-cicd/npm-virtual/"
    npmPublishRegistry: "https://europe-west1-npm.pkg.dev/siren-cicd/npm-standard/"
    npmAlwaysAuth: true
