nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.5.1.cjs

npmPublishRegistry: "https://europe-west1-npm.pkg.dev/siren-cicd/npm-standard/"

npmScopes:
  antv:
    npmRegistryServer: "https://europe-west1-npm.pkg.dev/siren-cicd/npm-virtual/"

