#!/usr/bin/env groovy
library 'jenkins-lib'

pipeline {

  agent {
    kubernetes {
      cloud getKubernetesClusterName()
      yaml readK8sConfig('build', '8Gi', '4')
    }
  }

  options {
    timestamps()
    ansiColor('xterm')
  }

  environment {
    SCMVARS = null
    CREDENTIALS_ID='86f3b7e9-aec0-4914-bc4c-24bfa709fab8'
    CI=true
  }

  stages {
    stage ('Checkout') {
      steps {
        checkout scm
      }
    }

    stage ('Boostrap') {
      steps {
        installNode()
        withCredentials([file(credentialsId: 'gcloud-jenkins-sirencicd', variable: 'GCLOUD_KEY_FILE')]) {
          sh 'gcloud auth activate-service-account --key-file="${GCLOUD_KEY_FILE}"'
          sh 'npm run auth'
          sh 'yarn'
          sh 'yarn bootstrap:ci'
        }
      }
    }

    stage('Deploy') {
      steps {
        script {
          ['graphin'].each {
            sh "cd packages/${it} && yarn build && yarn npm publish && cd .."
          }
        }
      }
    }
  }
}
